[package]
name = "enum_struct_for_data"
version = "0.1.0"
authors = ["Muhammad Muneeb Waseem <muneebwaseem78@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
